<?php

declare(strict_types=1);

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\File;

/**
 * E18 — `php artisan chatbot:install`.
 *
 * The command mutates the filesystem (publish + .env + stubs + layout). Each
 * test cleans the paths it will touch BEFORE and AFTER running: the
 * `beforeEach` guarantees a clean input state; the `afterEach` prevents the
 * views published under `resources/views/vendor/chatbot` from lingering after
 * the last test and shadowing the package views in later suites (published
 * views take resolution priority).
 */
function installCommandCleanup(): void
{
    $files = new Filesystem;

    // Stubs generated by previous runs.
    foreach ([app_path('Chatbot')] as $dir) {
        if ($files->isDirectory($dir)) {
            $files->deleteDirectory($dir);
        }
    }

    // Published config/lang/views (the publish would overwrite, but we also
    // want to verify it creates them from scratch).
    foreach ([config_path('chatbot.php'), resource_path('views/vendor/chatbot')] as $target) {
        if ($files->isDirectory($target)) {
            $files->deleteDirectory($target);
        } elseif ($files->isFile($target)) {
            $files->delete($target);
        }
    }

    // .env and .env.example created by previous tests.
    foreach ([base_path('.env'), base_path('.env.example')] as $env) {
        if ($files->isFile($env)) {
            $files->delete($env);
        }
    }

    // Test layouts.
    $layoutDir = resource_path('views/layouts');
    if ($files->isDirectory($layoutDir)) {
        $files->deleteDirectory($layoutDir);
    }
}

beforeEach(function () {
    installCommandCleanup();
});

afterEach(function () {
    installCommandCleanup();
});

it('runs end-to-end in --no-interaction mode and is idempotent', function () {
    File::put(base_path('.env'), "APP_NAME=Test\nAPP_ENV=testing\n");
    File::put(base_path('.env.example'), "APP_NAME=Test\nAPP_ENV=testing\n");

    $exit = $this->artisan('chatbot:install', ['--no-interaction' => true])->run();

    expect($exit)->toBe(0)
        ->and(file_exists(config_path('chatbot.php')))->toBeTrue()
        ->and(file_exists(app_path('Chatbot/ChatbotScopeResolver.php')))->toBeTrue();

    $env = File::get(base_path('.env'));
    expect($env)
        ->toContain('CHATBOT_PROVIDER=anthropic')
        ->and($env)->toContain('CHATBOT_MODEL=claude-sonnet-4-6')
        ->and($env)->toContain('ANTHROPIC_API_KEY=')
        ->and($env)->toContain('CHATBOT_AUTH_RESOLVER=');

    // No-interactive does NOT generate an example tool nor inject a layout.
    expect(file_exists(app_path('Chatbot/Tools/ListMyInvoicesTool.php')))->toBeFalse();

    // Second run: the keys must not appear twice.
    $exit2 = $this->artisan('chatbot:install', ['--no-interaction' => true])->run();
    expect($exit2)->toBe(0);

    $env2 = File::get(base_path('.env'));
    expect(substr_count($env2, 'CHATBOT_PROVIDER='))->toBe(1)
        ->and(substr_count($env2, 'CHATBOT_MODEL='))->toBe(1)
        ->and(substr_count($env2, 'ANTHROPIC_API_KEY='))->toBe(1);
});

it('preserves an existing API key value on re-run (overwrite=false)', function () {
    File::put(base_path('.env'), "ANTHROPIC_API_KEY=sk-real-secret\n");

    $this->artisan('chatbot:install', ['--no-interaction' => true])->run();

    $env = File::get(base_path('.env'));
    expect($env)->toContain('ANTHROPIC_API_KEY=sk-real-secret');
});

it('overwrites CHATBOT_PROVIDER with the latest choice (overwrite=true)', function () {
    File::put(base_path('.env'), "CHATBOT_PROVIDER=openai\n");

    $this->artisan('chatbot:install', ['--no-interaction' => true])->run();

    $env = File::get(base_path('.env'));
    expect($env)->toContain('CHATBOT_PROVIDER=anthropic')
        ->and($env)->not->toContain('CHATBOT_PROVIDER=openai');
});

it('skips .env writes silently when no .env file exists', function () {
    expect(file_exists(base_path('.env')))->toBeFalse();

    $exit = $this->artisan('chatbot:install', ['--no-interaction' => true])->run();

    expect($exit)->toBe(0)
        ->and(file_exists(base_path('.env')))->toBeFalse();
});

it('runs interactive happy path: provider/model/scope yes, tenant no, addendum no, example tool yes, layout no', function () {
    File::put(base_path('.env'), "");

    $this->artisan('chatbot:install')
        ->expectsQuestion('LLM provider (anthropic, openai, groq, gemini, mistral, ollama, …)', 'openai')
        ->expectsQuestion('Model to use', 'gpt-4o')
        ->expectsConfirmation('Generate a ScopeResolver stub in `app/Chatbot/`?', 'yes')
        ->expectsQuestion('ScopeResolver class name', 'MyResolver')
        ->expectsConfirmation('Does your host need tenant scope (multi-corporation, multi-event, etc.)?', 'no')
        ->expectsConfirmation('Publish the system prompt "addendum" view? (additional domain-specific instructions)', 'no')
        ->expectsConfirmation('Generate an example tool (ListMyInvoicesTool) in app/Chatbot/Tools/?', 'yes')
        ->expectsQuestion('Absolute or relative path of the layout to inject the widget into (empty = skip)', '')
        ->assertExitCode(0);

    $env = File::get(base_path('.env'));
    expect($env)->toContain('CHATBOT_PROVIDER=openai')
        ->and($env)->toContain('CHATBOT_MODEL=gpt-4o')
        ->and($env)->toContain('OPENAI_API_KEY=')
        ->and(file_exists(app_path('Chatbot/MyResolver.php')))->toBeTrue()
        ->and(file_exists(app_path('Chatbot/Tools/ListMyInvoicesTool.php')))->toBeTrue();

    $tool = File::get(app_path('Chatbot/Tools/ListMyInvoicesTool.php'));
    expect($tool)
        ->toContain('class ListMyInvoicesTool extends BaseBackendTool')
        ->and($tool)->toContain("return 'list_my_invoices';");
});

it('generates a tenant resolver stub when the user opts in', function () {
    File::put(base_path('.env'), "");

    $this->artisan('chatbot:install')
        ->expectsQuestion('LLM provider (anthropic, openai, groq, gemini, mistral, ollama, …)', 'anthropic')
        ->expectsQuestion('Model to use', 'claude-sonnet-4-6')
        ->expectsConfirmation('Generate a ScopeResolver stub in `app/Chatbot/`?', 'no')
        ->expectsConfirmation('Does your host need tenant scope (multi-corporation, multi-event, etc.)?', 'yes')
        ->expectsQuestion('TenantResolver class name', 'MyTenantResolver')
        ->expectsConfirmation('Publish the system prompt "addendum" view? (additional domain-specific instructions)', 'no')
        ->expectsConfirmation('Generate an example tool (ListMyInvoicesTool) in app/Chatbot/Tools/?', 'no')
        ->expectsQuestion('Absolute or relative path of the layout to inject the widget into (empty = skip)', '')
        ->assertExitCode(0);

    $path = app_path('Chatbot/MyTenantResolver.php');
    expect(file_exists($path))->toBeTrue();

    $contents = File::get($path);
    expect($contents)
        ->toContain('class MyTenantResolver implements TenantResolver')
        ->and($contents)->toContain('resolveAccessibleTenantIds');
});

it('publishes the system_prompt_addendum view when requested', function () {
    File::put(base_path('.env'), "");

    $this->artisan('chatbot:install')
        ->expectsQuestion('LLM provider (anthropic, openai, groq, gemini, mistral, ollama, …)', 'anthropic')
        ->expectsQuestion('Model to use', 'claude-sonnet-4-6')
        ->expectsConfirmation('Generate a ScopeResolver stub in `app/Chatbot/`?', 'no')
        ->expectsConfirmation('Does your host need tenant scope (multi-corporation, multi-event, etc.)?', 'no')
        ->expectsConfirmation('Publish the system prompt "addendum" view? (additional domain-specific instructions)', 'yes')
        ->expectsConfirmation('Generate an example tool (ListMyInvoicesTool) in app/Chatbot/Tools/?', 'no')
        ->expectsQuestion('Absolute or relative path of the layout to inject the widget into (empty = skip)', '')
        ->assertExitCode(0);

    $path = resource_path('views/vendor/chatbot/system_prompt_addendum.blade.php');
    expect(file_exists($path))->toBeTrue();
    expect(File::get($path))->toContain('Additional domain rules');
});

it('detects an existing layouts/app.blade.php and injects the widget once', function () {
    File::put(base_path('.env'), "");

    $layoutDir = resource_path('views/layouts');
    File::ensureDirectoryExists($layoutDir);
    $layoutPath = $layoutDir . '/app.blade.php';
    File::put($layoutPath, "<html>\n<body>\n  @yield('content')\n</body>\n</html>\n");

    $this->artisan('chatbot:install')
        ->expectsQuestion('LLM provider (anthropic, openai, groq, gemini, mistral, ollama, …)', 'anthropic')
        ->expectsQuestion('Model to use', 'claude-sonnet-4-6')
        ->expectsConfirmation('Generate a ScopeResolver stub in `app/Chatbot/`?', 'no')
        ->expectsConfirmation('Does your host need tenant scope (multi-corporation, multi-event, etc.)?', 'no')
        ->expectsConfirmation('Publish the system prompt "addendum" view? (additional domain-specific instructions)', 'no')
        ->expectsConfirmation('Generate an example tool (ListMyInvoicesTool) in app/Chatbot/Tools/?', 'no')
        // The prompt includes the detected layout path in quotes dynamically;
        // expectsConfirmation matches by substring if the question is stable.
        ->expectsConfirmation('Detected Blade layout(s): resources/views/layouts/app.blade.php. Inject the widget into the first one?', 'yes')
        ->assertExitCode(0);

    $contents = File::get($layoutPath);
    expect($contents)
        ->toContain('<!-- chatbot:widget -->')
        ->and($contents)->toContain('<chatbot-widget></chatbot-widget>')
        ->and(substr_count($contents, '<!-- chatbot:widget -->'))->toBe(1);

    // Second run: the marker is present, it is not injected again.
    $this->artisan('chatbot:install', ['--no-interaction' => true])->run();
    // No-interactive does not touch the layout, but let's verify the marker stays at 1.
    expect(substr_count(File::get($layoutPath), '<!-- chatbot:widget -->'))->toBe(1);
});

it('sets CHATBOT_AUTH_RESOLVER=gate when Spatie is not installed (no-interaction)', function () {
    // Spatie is not installed in the default test matrix; we verify it.
    expect(class_exists(\Spatie\Permission\PermissionServiceProvider::class))->toBeFalse();

    File::put(base_path('.env'), "");

    $this->artisan('chatbot:install', ['--no-interaction' => true])->run();

    expect(File::get(base_path('.env')))->toContain('CHATBOT_AUTH_RESOLVER=gate');
});
