<?php

declare(strict_types=1);

namespace Rnkr69\LaraChatbot\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Validates the payload of the endpoint `POST /chatbot/conversations` (E10).
 *
 *   - `title`    optional. Up to 200 chars (covers titles generated by the
 *                LLM after the first messages and those the host wants to
 *                inject manually).
 *   - `metadata` optional. Free-form array that the host app uses to store
 *                provider/model overrides (E08 reads them from
 *                `Conversation->metadata->provider/model`), tags, flags, etc.
 *                It is persisted as-is in the JSON column.
 */
class StoreConversationRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    /**
     * @return array<string, array<int, mixed>>
     */
    public function rules(): array
    {
        return [
            'title'    => ['nullable', 'string', 'max:200'],
            'metadata' => ['nullable', 'array'],
        ];
    }
}
